### Site Settings ###
title               : Wei Jie
description         : >-
                      <style>
                      .button {
                        display: flex;
                        align-items: center;
                        justify-content: center;
                        padding: 5px;
                        width: 50%;
                        background: #007BFF;
                        text-align: center;
                        border-radius: 5px;
                        color: white;
                        font-weight: bold;
                        line-height: 25px;
                        margin-top: 3%;
                        margin-left: auto;
                        margin-right: auto;
                        text-decoration: none;
                        color: white;
                      }
                      </style>
                      
                      Welcome to my portfolio website, where I'll be showcasing my projects and other stuff.
                      <a style="background:#007BFF" class='button' target='_blank' rel='noopener noreferrer' href='https://Cwjiee.github.io/assets/pdf/resume.pdf'>
                        CV/Resume
                      </a>
baseurl             : ""                                # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : Cwjiee/Cwjiee.github.io           # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true                              # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Chong Wei Jie
  image             : https://Cwjiee.github.io/assets/img/portfolio-pic.jpg
# behance           : your_username
# dribbble          : your_username
  email             : jackchong398.com
# facebook          : your_username
  github            : Cwjiee
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : chong-wei-jie-04a7b1279
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
# buymeacoffee:
#  enabled: false
#  username: your_username
#  color: "#007bff"
#  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
#  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
